/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/about/index" |
  "/subPages/etf/detail" |
  "/subPages/etf/index" |
  "/subPages/etf/performance" |
  "/subPages/etf/profile" |
  "/subPages/shixi-guide/asset-detail" |
  "/subPages/shixi-guide/index-list" |
  "/subPages/tamp/demo" |
  "/subPages/tamp/index" |
  "/subPages/tamp/marketing" |
  "/subPages/tools/entry" |
  "/subPages/valuation-tool/holdings-add" |
  "/subPages/valuation-tool/holdings-edit" |
  "/subPages/valuation-tool/holdings-sync" |
  "/subPages/valuation-tool/holdings-upload" |
  "/subPages/valuation-tool/holdings" |
  "/subPages/valuation-tool/index" |
  "/subPages/valuation-tool/mine-scan" |
  "/subPages/valuation-tool/result" |
  "/subPages/valuation-tool/search" |
  "/subPages/valuation-tool/watchlist" |
  "/subPages/tools/demo/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/about/index" | "/subPages/valuation-tool/index" | "/subPages/valuation-tool/watchlist" | "/subPages/valuation-tool/holdings"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
